title: "KB"
theme: minima
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# For Project Pages, set these (and remove comments):
# url: "https://<USER>.github.io"
# baseurl: "/<REPO>"

defaults:
  - scope: { path: "kb" }
    values: { layout: "kb" }
