title: "KB"
theme: minima
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Project Pages の場合は設定（ユーザー/組織Pagesなら url のみ）
# url: "https://<USER>.github.io"
# baseurl: "/<REPO>"

defaults:
  - scope: { path: "kb" }
    values: { layout: "kb" }
